[package]
name = "server-manager"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """server-manager is a rust library for managing server processes. It encapsulates service startup, shutdown, and background daemon mode. Users can specify the PID file, log file paths, and other configurations through custom settings, while also passing in their own asynchronous server function for execution. The library supports both synchronous and asynchronous operations. On Unix and Windows platforms, it enables background daemon processes."""
keywords = ["manager", "processes", "libc", "linux", "unix"]
repository.workspace = true
categories = ["development-tools"]
exclude.workspace = true

[dependencies]
tokio = { workspace = true }
