[package]
name = "compare_version"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A Rust library for comparing semantic versioning strings and checking version compatibility."
keywords = ["version", "comparison", "semver", "rust"]
repository.workspace = true
categories = ["algorithms", "development-tools", "rust-patterns"]
