[workspace]
resolver = "2"
members = [
    "crates/bin-encode-decode",
    "crates/china_identification_card",
    "crates/chunkify",
    "crates/clonelicious",
    "crates/color-output",
    "crates/compare-version",
    "crates/crates-cli",
    "crates/file-operation",
    "crates/future-fn",
    "crates/gtl",
    "crates/hot-restart",
    "crates/instrument-level",
    "crates/jwt-service",
    "crates/lombok-macros",
    "crates/recoverable-spawn",
    "crates/recoverable-thread-pool",
    "crates/server-manager",
    "crates/std-macro-extensions",
    "crates/tcp-request",
    "crates/tcplane",
    "crates/udp",
    "crates/udp-request",
]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT"
readme = "README.md"
authors = ["root@ltpp.vip"]
repository = "https://github.com/crates-dev/ctares"
exclude = ["target", "Cargo.lock", "sh", ".github"]
