[package]
name = "udp"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A lightweight and efficient Rust library for building UDP servers with request-response handling."
keywords = ["udp", "request", "response", "server", "network"]
repository.workspace = true
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[dependencies]
tokio = { workspace = true }
