[package]
name = "gtl"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """gtl is a Git-based tool designed to simplify the management of multiple remote repositories. It extends Git's functionality by providing one-click initialization and pushing to multiple remote repositories, making it especially useful for developers who need to maintain multiple remote repositories simultaneously."""
keywords = ["git", "helper", "remote", "tool", "repositories"]
repository.workspace = true
categories = ["data-structures", "development-tools"]
exclude.workspace = true

[dependencies]
toml = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
