[package]
name = "tcp-request"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """A Rust library for sending raw TCP requests, with features for handling responses, managing redirects, and working with compressed data over TCP connections."""
keywords = ["http", "request", "response", "tcp", "redirect"]
repository.workspace = true
categories = ["network-programming", "web-programming"]
exclude.workspace = true
