use super::*;

/// Represents the internal, mutable state of the TCP server.
///
/// This struct consolidates all the core components required for the server to operate,
/// including configuration and handler list. It is not intended to be used directly by end-users,
/// but rather wrapped within the `Server` struct for thread-safe access.
///
/// Accessors are generated by `#[derive(Data)]`; the configuration accessor is
/// `get_server_config` (named after the field).
#[derive(Clone, Data)]
pub struct ServerData {
    /// Stores the server's configuration settings, such as address, port, and buffer size.
    #[get_mut(pub(crate))]
    #[set(pub(crate))]
    pub(crate) server_config: ServerConfigData,
    /// A collection of request hooks that are invoked for each incoming connection.
    #[get_mut(pub(crate))]
    #[set(pub(crate))]
    pub(crate) hook: ServerHookList,
    /// A collection of task panic handlers that are invoked when a panic occurs during connection processing.
    #[get_mut(pub(crate))]
    #[set(pub(crate))]
    pub(crate) task_panic: ServerHookList,
    /// The error handlers for server operations.
    #[get_mut(pub(crate))]
    #[set(pub(crate))]
    pub(crate) read_error: ServerHookList,
}

/// The primary server structure that provides a thread-safe interface to the server's state.
///
/// This struct acts as a public-facing wrapper around an `Arc<RwLock<ServerData>>`.
/// It allows multiple parts of the application to safely share and modify the server's
/// configuration and state across different threads and asynchronous tasks.
#[derive(Clone)]
pub struct Server(pub(super) ArcRwLock<ServerData>);

/// Represents the hooks for managing the server's lifecycle, specifically for waiting and shutting down.
///
/// Accessors are generated by `#[derive(Data)]`; the hook getters return owned
/// `Arc` clones via `type(clone)`.
#[derive(Clone, Data)]
pub struct ServerControlHook {
    /// A hook that returns a future, which completes when the server's main task finishes.
    #[get(type(clone))]
    #[get(pub(crate))]
    #[get_mut(pub(crate))]
    #[set(pub(crate))]
    pub(crate) wait_hook:
        Arc<dyn Fn() -> Pin<Box<dyn Future<Output = ()> + Send + 'static>> + Send + Sync>,
    /// A hook that, when called, initiates a graceful shutdown of the server.
    #[get(type(clone))]
    #[get(pub(crate))]
    #[get_mut(pub(crate))]
    #[set(pub(crate))]
    pub(crate) shutdown_hook:
        Arc<dyn Fn() -> Pin<Box<dyn Future<Output = ()> + Send + 'static>> + Send + Sync>,
}
