[package]
name = "color-output"
version = "10.1.3"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """An atomic output library based on Rust that supports output functionalities through functions, builders, and other methods. It allows customization of text and background colors."""
keywords = ["output", "console", "log", "print", "color"]
repository = "https://github.com/crates-dev/color-output"
categories = ["command-line-interface", "development-tools", "visualization"]
exclude = ["target", "Cargo.lock", "sh", ".github"]

[dependencies]
hyperlane-time = { workspace = true }
