[package]
name = "color-output"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """An atomic output library based on Rust that supports output functionalities through functions, builders, and other methods. It allows customization of text and background colors."""
keywords = ["output", "console", "log", "print", "color"]
repository.workspace = true
categories = ["command-line-interface", "development-tools", "visualization"]
exclude.workspace = true

[dependencies]
hyperlane-time = { workspace = true }
