[package]
name = "chunkify"
version = "0.6.60"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """A simple and efficient chunking library for Rust."""
keywords = ["http", "file", "chunk", "upload", "web"]
repository = "https://github.com/crates-dev/chunkify.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github",
    "logs",
    "uploads",
    "**/*.log",
]

[dependencies]
file-operation = { workspace = true }

dashmap = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
twox-hash = { workspace = true }

[profile.dev]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
