[package]
name = "recoverable-spawn"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """A thread that supports automatic recovery from panics, allowing threads to restart after a panic. Useful for resilient and fault-tolerant concurrency in network and web programming."""
keywords = ["time", "hyperlane", "day", "format", "lang"]
repository.workspace = true
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[dependencies]
tokio = { workspace = true }
once_cell = { workspace = true }
