[package]
name = "bin-encode-decode"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A high-performance binary encode and decode library that supports customizable character sets beyond Base64."
keywords = [
    "binaryencode",
    "decode",
    "customcharset",
    "highperformance",
    "base64alternative",
]
repository.workspace = true
categories = ["encoding"]
