use super::*;

/// Represents data captured from a panic.
///
/// This structure holds information about a panic that occurred during
/// request processing, including the panic message and location if available.
///
/// Accessors are generated by `#[derive(Data)]`; the optional location getter
/// returns an owned `Option<String>` via `type(clone)`.
#[derive(Clone, Data, Debug)]
pub struct PanicData {
    /// The panic message.
    pub(super) message: String,
    /// The location where the panic occurred (file and line).
    #[get(pub, type(clone))]
    pub(super) location: Option<String>,
}
