use super::*;

/// TCP request structure containing configuration and response data.
///
/// Accessors are generated by `#[derive(Data)]` at `pub(crate)` visibility;
/// unused mutable accessors are skipped to avoid dead code.
#[derive(Clone, Data, Debug)]
pub struct TcpRequest {
    /// Thread-safe configuration for the request.
    #[get(pub(crate))]
    #[get_mut(skip)]
    #[set(skip)]
    pub(crate) config: ArcRwLock<Config>,
    /// Thread-safe binary response storage.
    #[get(pub(crate))]
    #[get_mut(skip)]
    #[set(pub(crate))]
    pub(crate) response: ArcRwLock<TcpResponseBinary>,
}
