[package]
name = "clonelicious"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """A Rust macro library that simplifies cloning and closure execution. The `clone!` macro automatically clones variables and immediately executes the closure with the cloned values, streamlining common patterns in Rust programming."""
keywords = ["standard", "macro", "extensions", "structures", "simplifying"]
repository.workspace = true
categories = ["data-structures", "development-tools"]
exclude.workspace = true

[dev-dependencies]
tokio = { workspace = true }
