[package]
name = "tokio-broadcast"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """tokio-broadcast is a lightweight and ergonomic wrapper over Tokio’s broadcast channel designed for easy-to-use publish-subscribe messaging in async Rust applications. It simplifies the native Tokio broadcast API by providing a straightforward interface for broadcasting messages to multiple subscribers with minimal boilerplate."""
keywords = ["time", "hyperlane", "broadcast", "tokio"]
repository.workspace = true
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[dependencies]
dashmap = { workspace = true }
twox-hash = { workspace = true }
tokio = { workspace = true }