use super::*;

/// Main configuration structure for log file output.
///
/// Controls where logs are stored and their maximum size limits.
/// Use FileLogger::new() to create an instance with custom settings.
///
/// Accessors are generated by `#[derive(Data)]`; the `String` setters accept
/// any `impl AsRef<str>` via `#[set(type(AsRef<str>))]`.
#[derive(Clone, Data)]
pub struct FileLogger {
    /// The directory path where log files will be stored.
    #[set(type(AsRef<str>))]
    pub(super) path: String,
    /// The maximum allowed size (in bytes) for individual log files.
    /// Set to 0 to disable logging.
    pub(super) limit_file_size: usize,
    /// Subdirectory name for trace logs.
    #[set(type(AsRef<str>))]
    pub(super) trace_dir: String,
    /// Subdirectory name for debug logs.
    #[set(type(AsRef<str>))]
    pub(super) debug_dir: String,
    /// Subdirectory name for info logs.
    #[set(type(AsRef<str>))]
    pub(super) info_dir: String,
    /// Subdirectory name for warn logs.
    #[set(type(AsRef<str>))]
    pub(super) warn_dir: String,
    /// Subdirectory name for error logs.
    #[set(type(AsRef<str>))]
    pub(super) error_dir: String,
}
