[package]
name = "udp-request"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """A simple UDP request library for sending and receiving UDP packets, designed to handle network communication in Rust applications."""
keywords = ["udp", "net", "response", "request", "tool"]
repository.workspace = true
categories = ["network-programming", "web-programming"]
exclude.workspace = true
