[package]
name = "udp-request"
version = "0.4.1"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """A simple UDP request library for sending and receiving UDP packets, designed to handle network communication in Rust applications."""
keywords = ["udp", "net", "response", "request", "tool"]
repository = "https://github.com/crates-dev/udp-request.git"
categories = ["network-programming", "web-programming"]
exclude = ["target", "Cargo.lock", "sh", ".github"]
