[package]
name = "hot-restart"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """A Rust library for hot restarting applications without downtime. Provides seamless process replacement for servers and long-running services, enabling zero-downtime updates and configuration reloads."""
keywords = ["hot", "restart", "cargo", "watch", "file"]
repository.workspace = true
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[dev-dependencies]
tokio = { workspace = true }
