[package]
name = "instrument-level"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A Rust procedural macro collection providing convenient tracing instrumentation macros for different log levels (trace, debug, info, warn, error). This crate simplifies the process of adding tracing spans to functions with pre-configured log levels."
keywords = ["http", "request", "response", "tcp", "cross-platform"]
repository.workspace = true
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["full"] }

[dev-dependencies]
tracing = { workspace = true }
