[package]
name = "china_identification_card"
version = "1.2.2"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = "A Rust library for validating Chinese identification card numbers based on official rules and checksums."
keywords = ["china", "id", "identification", "card", "validation"]
repository = "https://github.com/crates-dev/china_identification_card"
categories = ["authentication", "data-structures", "development-tools"]
