[package]
name = "china_identification_card"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A Rust library for validating Chinese identification card numbers based on official rules and checksums."
keywords = ["china", "id", "identification", "card", "validation"]
repository.workspace = true
categories = ["authentication", "data-structures", "development-tools"]
