use super::*;

/// Represents a UDP request.
///
/// This struct holds the configuration and response for a UDP request.
///
/// Accessors are generated by `#[derive(Data)]` at `pub(crate)` visibility;
/// unused mutable accessors are skipped to avoid dead code.
#[derive(Clone, Data, Debug)]
pub struct UdpRequest {
    /// The configuration for the UDP request, wrapped in an `Arc<RwLock<>>`.
    #[get(pub(crate))]
    #[get_mut(skip)]
    #[set(skip)]
    pub(crate) config: ArcRwLock<Config>,
    /// The response of the UDP request, wrapped in an `Arc<RwLock<>>`.
    #[get(pub(crate))]
    #[get_mut(skip)]
    #[set(pub(crate))]
    pub(crate) response: ArcRwLock<UdpResponseBinary>,
}
