[package]
name = "jwt-service"
version = "0.3.4"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """A high-performance async library for JWT (JSON Web Token) authentication and authorization. Supports token generation, validation, and custom claims with optimized memory usage, ideal for HTTP clients/servers and web applications."""
keywords = ["jwt", "authentication", "token", "authorization", "json-web-token"]
repository = "https://github.com/crates-dev/jwt-service.git"
categories = ["network-programming", "web-programming"]
exclude = ["target", "Cargo.lock", "sh", ".github"]

[dependencies]
jsonwebtoken = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
