use super::*;

/// Builder for creating and configuring TCP requests.
///
/// Accessors are generated by `#[derive(Data)]` at `pub(crate)` visibility;
/// unused mutable getters are skipped to avoid dead code.
#[derive(Clone, Data, Debug)]
pub struct RequestBuilder {
    /// The TCP request being configured.
    #[get(pub(crate))]
    #[get_mut(skip)]
    #[set(pub(crate))]
    pub(crate) tcp_request: TcpRequest,
    /// The built TCP request instance.
    #[get(pub(crate))]
    #[get_mut(skip)]
    #[set(pub(crate))]
    pub(crate) builder: TcpRequest,
}
