[package]
name = "file-operation"
version = "0.9.5"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
description = """A Rust library providing comprehensive utilities for file operations with both sync/async support. Includes operations for copy, delete, move, read and write files. Simplifies file handling in Rust projects with safe and efficient methods for file manipulation and metadata querying."""
keywords = ["time", "hyperlane", "day", "format", "lang"]
repository = "https://github.com/crates-dev/file-operation.git"
categories = ["network-programming", "web-programming"]
exclude = ["target", "Cargo.lock", "sh", ".github"]

[dependencies]
tokio = { workspace = true }
