[package]
name = "future-fn"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """A Rust library providing macros to simplify the creation of asynchronous closures with external state captured by move. Useful for structuring asynchronous code with ease and clarity."""
keywords = ["standard", "macro", "extensions", "structures", "simplifying"]
repository.workspace = true
categories = ["data-structures", "development-tools"]
exclude.workspace = true

[dev-dependencies]
tokio = { workspace = true }
