use super::*;

/// A builder for creating and configuring a `UdpRequest`.
///
/// This struct provides a fluent interface for building a `UdpRequest`.
///
/// Accessors are generated by `#[derive(Data)]` at `pub(crate)` visibility;
/// unused mutable getters are skipped to avoid dead code.
#[derive(Clone, Data, Debug)]
pub struct RequestBuilder {
    /// The `UdpRequest` instance being built.
    #[get(pub(crate))]
    #[get_mut(skip)]
    #[set(pub(crate))]
    pub(crate) udp_request: UdpRequest,
    /// A mutable `UdpRequest` instance used for configuration.
    #[get(pub(crate))]
    #[get_mut(skip)]
    #[set(pub(crate))]
    pub(crate) builder: UdpRequest,
}
