[package]
name = "chunkify"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """A simple and efficient chunking library for Rust."""
keywords = ["http", "file", "chunk", "upload", "web"]
repository.workspace = true
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[dependencies]
file-operation = { workspace = true }

tokio = { workspace = true }
dashmap = { workspace = true }
once_cell = { workspace = true }
twox-hash = { workspace = true }
